version: '3.1'

services:

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgre
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: progresspro
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: manuelreyesjimenez11@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "80:80"
    depends_on:
      - postgres

volumes:
  postgres_data:

